export var Entities: string[] = [
  'category',
  'user',
  'jwtentity',
  'filmactor',
  'address',
  'userrole',
  'customer',
  'film',
  'staff',
  'store',
  'rolepermission',
  'userpermission',
  'city',
  'userpreference',
  'role',
  'tokenverification',
  'payment',
  'language',
  'rental',
  'actor',
  'permission',
  'country',
  'filmcategory',
  'inventory',
];

export var AuthEntities: string[] = ['user', 'role', 'permission', 'rolepermission', 'userpermission', 'userrole'];
